# Generated by Django 2.0.1 on 2018-07-05 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qjcff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jcff', models.CharField(max_length=100, verbose_name='检测方法')),
                ('jcffdz', models.FileField(upload_to='bc_test/jcff/%Y/%m/%d', verbose_name='检测方法文件')),
            ],
            options={
                'verbose_name': '检测方法',
                'verbose_name_plural': '检测方法基础表',
                'db_table': 'Qjcff',
            },
        ),
        migrations.CreateModel(
            name='Qjcxm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zbmc', models.CharField(max_length=50, verbose_name='检测项目名称')),
                ('dw', models.CharField(max_length=50, verbose_name='单位')),
                ('jcffid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjcff', verbose_name='检测方法编号')),
            ],
            options={
                'verbose_name': '检测项目',
                'verbose_name_plural': '检测项目基础表',
                'db_table': 'qjcxm',
            },
        ),
        migrations.CreateModel(
            name='Qjybg',
            fields=[
                ('bgbh', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='报告编号')),
                ('cpmc', models.CharField(max_length=50, verbose_name='名称')),
                ('scrq', models.DateTimeField(verbose_name='生产日期')),
                ('ylpc', models.CharField(max_length=50, verbose_name='批号')),
                ('gg', models.CharField(max_length=50, verbose_name='规格')),
                ('cyrq', models.DateTimeField(verbose_name='抽样日期')),
                ('jyyj', models.CharField(blank=True, max_length=1000, null=True, verbose_name='检验依据')),
                ('jyjl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='检验结论')),
                ('fl', models.CharField(choices=[('jc', '进场检验'), ('cc', '出场检验')], max_length=20, verbose_name='分类')),
                ('pzr', models.CharField(blank=True, max_length=20, null=True, verbose_name='批准人')),
                ('shr', models.CharField(blank=True, max_length=20, null=True, verbose_name='审核人')),
                ('bzr', models.CharField(blank=True, max_length=20, null=True, verbose_name='制编人')),
                ('sh', models.BooleanField(default=True, verbose_name='审核状态')),
                ('bz', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('jybgfile', models.FileField(upload_to='bc_test/jybg/%Y/%m/%d', verbose_name='检验报告文件')),
            ],
            options={
                'verbose_name': '检验报告',
                'verbose_name_plural': '检验报告',
                'db_table': 'qjybg',
            },
        ),
        migrations.CreateModel(
            name='Qjybgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmname', models.CharField(max_length=20, verbose_name='检测项目名称')),
                ('dw', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('bzz', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='标准值')),
                ('pdz', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='判定值')),
                ('jcz', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='检测值')),
                ('jcff', models.CharField(max_length=100, verbose_name='检测方法')),
                ('bz', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('pd', models.BooleanField(default=True, verbose_name='是否合格')),
                ('bgbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjybg', verbose_name='报告编号')),
                ('jcxm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjcxm', verbose_name='检测项目编号')),
            ],
            options={
                'verbose_name': '检验报告副表',
                'verbose_name_plural': '检验报告副表',
                'db_table': 'qjybgf',
            },
        ),
        migrations.CreateModel(
            name='Qjybz',
            fields=[
                ('bzid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='检验标准编号')),
                ('bzmc', models.CharField(max_length=50, verbose_name='标准名称')),
                ('zt', models.SmallIntegerField(blank=True, null=True, verbose_name='状态')),
                ('bz', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '检验标准',
                'verbose_name_plural': '检验标准',
                'db_table': 'qjybz',
            },
        ),
        migrations.CreateModel(
            name='QjybzF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdlower', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='标准值下限')),
                ('stdupper', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='标准值上限')),
                ('acplower', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='收货值上限')),
                ('acpupper', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='收货值下限')),
                ('bj', models.BooleanField(default=True, verbose_name='必检')),
                ('bzid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjybz', verbose_name='检验标准主表')),
                ('jcxmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjcxm', verbose_name='检测项目编号')),
            ],
            options={
                'verbose_name': '检验标准副表',
                'verbose_name_plural': '检验标准副表',
                'db_table': 'qjybzf',
            },
        ),
        migrations.CreateModel(
            name='Qypqy',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='样品编号')),
                ('cyrq', models.DateTimeField(auto_now_add=True, verbose_name='抽样日期')),
                ('cpmc', models.CharField(max_length=50, verbose_name='产品名称')),
                ('scrq', models.DateTimeField(verbose_name='生产日期')),
                ('ylpc', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品批号')),
                ('gg', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格')),
                ('cydd', models.CharField(blank=True, max_length=30, null=True, verbose_name='抽样地点')),
                ('cysl', models.CharField(max_length=50, verbose_name='样品数量')),
                ('cyjs', models.CharField(blank=True, max_length=50, null=True, verbose_name='抽样基数')),
                ('cyrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='抽样人ID')),
                ('ylid', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='bc_production.Scjhb', verbose_name='产品代码')),
            ],
            options={
                'verbose_name': '样品取样',
                'verbose_name_plural': '样品取样',
                'db_table': 'qypqy',
            },
        ),
        migrations.AddField(
            model_name='qjybg',
            name='qjybz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjybz', verbose_name='检验标准'),
        ),
        migrations.AddField(
            model_name='qjybg',
            name='qypqy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qypqy', verbose_name='样品编号'),
        ),
    ]
