# Generated by Django 2.0.1 on 2018-07-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qjcff',
            name='jcffdz',
            field=models.FileField(blank=True, null=True, upload_to='bc_test/jcff/%Y/%m/%d', verbose_name='检测方法文件'),
        ),
        migrations.AlterField(
            model_name='qjybg',
            name='cyrq',
            field=models.DateField(verbose_name='抽样日期'),
        ),
        migrations.AlterField(
            model_name='qjybg',
            name='jybgfile',
            field=models.FileField(blank=True, null=True, upload_to='bc_test/jybg/%Y/%m/%d', verbose_name='检验报告文件'),
        ),
        migrations.AlterField(
            model_name='qjybg',
            name='scrq',
            field=models.DateField(verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='qypqy',
            name='cyrq',
            field=models.DateField(auto_now_add=True, verbose_name='抽样日期'),
        ),
        migrations.AlterField(
            model_name='qypqy',
            name='scrq',
            field=models.DateField(verbose_name='生产日期'),
        ),
    ]
