# Generated by Django 2.0.1 on 2018-08-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_test', '0002_auto_20180705_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qjcxm',
            name='dw',
            field=models.CharField(blank=True, max_length=50, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='qjybg',
            name='cyrq',
            field=models.DateField(blank=True, verbose_name='抽样日期'),
        ),
        migrations.AlterField(
            model_name='qjybg',
            name='gg',
            field=models.CharField(blank=True, max_length=50, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='qypqy',
            name='ylid',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='bc_production.Scjhb', verbose_name='计划单号'),
        ),
    ]
