# Generated by Django 2.0.1 on 2018-09-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scjhb',
            fields=[
                ('spl', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='计划单号')),
                ('scrq', models.DateField(verbose_name='日期')),
                ('sl', models.IntegerField(verbose_name='生产数量')),
                ('cs', models.IntegerField(blank=True, null=True, verbose_name='批次数')),
                ('dw', models.CharField(default='kg', max_length=20, verbose_name='单位')),
                ('bc', models.IntegerField(blank=True, null=True, verbose_name='班次')),
                ('zt', models.BooleanField(default=True, verbose_name='启用')),
                ('bz', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('cpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_product.Cpml', verbose_name='产品编号')),
                ('xdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单人')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
                'db_table': 'scjhb',
            },
        ),
        migrations.CreateModel(
            name='Todaywork',
            fields=[
                ('ph', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='生产批号')),
                ('pldate', models.DateField(verbose_name='计划日期')),
                ('workno', models.IntegerField(verbose_name='生产顺序')),
                ('cpid', models.CharField(max_length=50, verbose_name='产品编号')),
                ('cpname', models.CharField(max_length=50, verbose_name='产品名称')),
                ('pbbh', models.CharField(max_length=50, verbose_name='配方编号')),
                ('pbname', models.CharField(max_length=50, verbose_name='配方名称')),
                ('worksl', models.IntegerField(default=1, verbose_name='任务次数')),
                ('plsl', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('scxh', models.IntegerField(blank=True, null=True, verbose_name='生产线号')),
                ('bc', models.IntegerField(blank=True, null=True, verbose_name='班次')),
                ('zt', models.BooleanField(default=True, verbose_name='启用')),
                ('bz', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('optionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单人')),
                ('spl', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='bc_production.Scjhb', verbose_name='生产单号')),
            ],
            options={
                'verbose_name': '生产计划明细',
                'verbose_name_plural': '生产计划明细',
                'db_table': 'todaywork',
            },
        ),
    ]
