# Generated by Django 2.0.1 on 2018-08-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bc_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scjhb',
            fields=[
                ('scph', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='生产批号')),
                ('scrq', models.DateField(verbose_name='生产日期')),
                ('cpname', models.CharField(max_length=50, verbose_name='产品名称')),
                ('pbbh', models.CharField(max_length=50, verbose_name='配方编号')),
                ('pbname', models.CharField(max_length=50, verbose_name='配方名称')),
                ('sl', models.IntegerField(verbose_name='生产数量')),
                ('cs', models.IntegerField(blank=True, null=True, verbose_name='批次数')),
                ('bzgg', models.CharField(blank=True, max_length=20, null=True, verbose_name='包装规格')),
                ('dw', models.CharField(default='kg', max_length=20, verbose_name='单位')),
                ('zt', models.BooleanField(default=True, verbose_name='启用')),
                ('bz', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('bc', models.IntegerField(blank=True, null=True, verbose_name='班次')),
                ('cpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_product.Cpml', verbose_name='产品编号')),
                ('xdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单人')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
                'db_table': 'scjhb',
            },
        ),
    ]
