# Generated by Django 2.0.1 on 2018-07-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bc_test', '0001_initial'),
        ('bc_production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scjhb',
            name='jybg',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjybg', verbose_name='检验报告'),
        ),
    ]
