# Generated by Django 2.0.1 on 2019-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scjhb',
            name='sl',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='生产数量'),
        ),
        migrations.AlterField(
            model_name='todaywork',
            name='plsl',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量'),
        ),
    ]
