# Generated by Django 2.0.1 on 2018-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaywork',
            name='optionid',
        ),
    ]
