# Generated by Django 2.0.1 on 2018-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaywork',
            name='ph',
            field=models.CharField(max_length=50, unique=True, verbose_name='生产批号'),
        ),
    ]
