# Generated by Django 2.0.1 on 2018-07-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0002_scjhb_jybg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scjhb',
            name='jybg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_test.Qjybg', verbose_name='检验报告'),
        ),
    ]
