# Generated by Django 2.0.1 on 2018-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0002_remove_todaywork_optionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaywork',
            name='bc',
        ),
    ]
