# Generated by Django 2.0.1 on 2018-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0004_auto_20180705_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaywork',
            name='pldate',
            field=models.DateField(verbose_name='计划日期'),
        ),
    ]
