# Generated by Django 2.0.1 on 2018-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_production', '0005_auto_20180705_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scjhb',
            name='dw',
            field=models.IntegerField(blank=True, choices=[(0, 'kg'), (1, 'g')], null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='scjhb',
            name='zt',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='todaywork',
            name='zt',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
