# Generated by Django 2.0.1 on 2019-05-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLNote_fb1',
            fields=[
                ('fplid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plno', models.IntegerField(verbose_name='配料顺序')),
                ('ylid', models.CharField(max_length=50, verbose_name='原料代码')),
                ('ylzl', models.FloatField(verbose_name='称量值')),
                ('llyl', models.FloatField(blank=True, null=True, verbose_name='理论值')),
                ('gc', models.CharField(blank=True, max_length=50, null=True, verbose_name=' 公差')),
                ('mz', models.FloatField(blank=True, null=True, verbose_name='毛重')),
                ('pz', models.FloatField(blank=True, null=True, verbose_name='皮重')),
                ('zsd', models.IntegerField(blank=True, null=True, verbose_name='整件数')),
                ('clr', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作称量人')),
                ('ltzl', models.FloatField(blank=True, null=True, verbose_name='零头重量')),
            ],
            options={
                'verbose_name': '配料记录',
                'verbose_name_plural': '配料记录',
                'db_table': 'PLNote_fb1',
            },
        ),
        migrations.CreateModel(
            name='PLNote_fb2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ylbarcode', models.CharField(max_length=50, verbose_name='原料条形码')),
                ('fplid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_batchingrecord.PLNote_fb1', verbose_name='配料记录副库ID')),
            ],
            options={
                'verbose_name': '配料记录',
                'verbose_name_plural': '配料记录',
                'db_table': 'PLNote_fb2',
            },
        ),
        migrations.CreateModel(
            name='PLNote_Main',
            fields=[
                ('plid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='混料编号')),
                ('pldatetime', models.DateTimeField(verbose_name='混料日期')),
                ('pbbh', models.CharField(max_length=50, verbose_name='配方编号')),
                ('actionid', models.CharField(max_length=50, verbose_name='操作员ID')),
                ('mz', models.FloatField(blank=True, null=True, verbose_name='复核毛重')),
                ('pz', models.FloatField(blank=True, null=True, verbose_name='复核皮重')),
                ('dw', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('bc', models.IntegerField(blank=True, null=True, verbose_name='班次')),
            ],
            options={
                'verbose_name': '配料记录',
                'verbose_name_plural': '配料记录',
                'db_table': 'PLNote_Main',
            },
        ),
        migrations.AddField(
            model_name='plnote_fb1',
            name='plid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_batchingrecord.PLNote_Main', verbose_name='混料编号'),
        ),
    ]
