# Generated by Django 2.0.1 on 2019-06-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_special', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='special',
            table='special',
        ),
    ]
