# Generated by Django 2.0.1 on 2018-06-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bc_formula', '0002_auto_20180629_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpml',
            fields=[
                ('cpid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='产品编号')),
                ('cpmc', models.CharField(max_length=50, verbose_name='产品名称')),
                ('dz', models.FloatField(blank=True, null=True, verbose_name='包装规格')),
                ('xkz', models.CharField(blank=True, max_length=50, verbose_name='产品许可证')),
                ('pw', models.CharField(blank=True, max_length=50, verbose_name='批准文号')),
                ('bz', models.CharField(blank=True, max_length=50, verbose_name='标准编号')),
                ('cpsx', models.FloatField(blank=True, null=True, verbose_name=' 打包上限')),
                ('cpxx', models.FloatField(blank=True, null=True, verbose_name='成品打包下限')),
                ('gg', models.CharField(blank=True, max_length=20, verbose_name='规格')),
                ('tempname', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签模板')),
                ('zbq', models.IntegerField(blank=True, null=True, verbose_name='质保期(天)')),
                ('cctj', models.CharField(blank=True, max_length=50, null=True, verbose_name='储存条件')),
                ('sptm', models.CharField(blank=True, max_length=20, verbose_name='商品条码')),
                ('cptp', models.ImageField(upload_to='bc_products')),
                ('cpgg', models.CharField(max_length=20, verbose_name='产品规格(含量,重量)')),
                ('cpsb', models.CharField(max_length=50, verbose_name='产品商标')),
                ('pbbh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bc_formula.Pb', verbose_name='配方编号')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品目录基础表',
                'db_table': 'cpml',
            },
        ),
    ]
