# Generated by Django 2.0.1 on 2019-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpml',
            name='cppic',
            field=models.ImageField(blank=True, null=True, upload_to='bc_products/cppic/%Y/%m/%d', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpsm',
            field=models.FileField(blank=True, null=True, upload_to='bc_products/cpsm/%Y/%m/%d', verbose_name='产品说明'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='tempname',
            field=models.FileField(blank=True, null=True, upload_to='bc_products/cptemp/%Y/%m/%d', verbose_name='成品标签模板'),
        ),
    ]
