# Generated by Django 2.0.1 on 2018-08-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpml',
            name='sptm',
        ),
    ]
