# Generated by Django 2.0.1 on 2018-08-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0002_auto_20180702_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpml',
            name='pbbh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_formula.Pb', verbose_name='配方编号'),
        ),
    ]
