# Generated by Django 2.0.1 on 2019-02-11 10:14

import bc_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0002_auto_20190116_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpml',
            name='bz',
        ),
        migrations.AddField(
            model_name='cpml',
            name='bzbh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标准编号'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cppic',
            field=models.ImageField(blank=True, null=True, upload_to=bc_product.models.user_directory_path, verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpsb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品商标'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpsm',
            field=models.FileField(blank=True, null=True, upload_to=bc_product.models.user_directory_path, verbose_name='产品说明'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpsx',
            field=models.FloatField(blank=True, null=True, verbose_name=' 包装上限'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpxkz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品许可证'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpxx',
            field=models.FloatField(blank=True, null=True, verbose_name='包装下限'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='dbz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='单包重'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='gg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='pw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='批准文号'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='tempname',
            field=models.FileField(blank=True, null=True, upload_to=bc_product.models.user_directory_path, verbose_name='成品标签模板'),
        ),
    ]
