# Generated by Django 2.0.1 on 2018-08-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0002_remove_cpml_sptm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpml',
            name='cpsx',
            field=models.IntegerField(blank=True, null=True, verbose_name=' 成品打包上限'),
        ),
        migrations.AlterField(
            model_name='cpml',
            name='cpxx',
            field=models.IntegerField(blank=True, null=True, verbose_name='成品打包下限'),
        ),
    ]
