# Generated by Django 2.0.1 on 2019-02-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_product', '0003_auto_20190211_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpml',
            name='pbbh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bc_formula.Pb', verbose_name='配方编号'),
        ),
    ]
