# Generated by Django 2.0.1 on 2018-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_rmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylinfo',
            name='dw',
            field=models.CharField(choices=[('0', 'kg'), ('1', 'g')], default='0', max_length=50, verbose_name='计量单位'),
        ),
    ]
