# Generated by Django 2.0.1 on 2018-12-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_rmaterial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, verbose_name='原料条码')),
                ('ylname', models.CharField(max_length=50, verbose_name='原料名称')),
                ('clph', models.CharField(blank=True, max_length=50, null=True, verbose_name='原料批号')),
                ('dbz', models.FloatField(verbose_name='单包重')),
                ('zl', models.FloatField(verbose_name='入库重量')),
                ('rdate', models.DateTimeField(verbose_name='入库日期')),
                ('scrq', models.DateTimeField(blank=True, null=True, verbose_name='生产日期')),
                ('gysname', models.CharField(max_length=50, verbose_name='供应商名称')),
                ('lotbar', models.CharField(blank=True, max_length=50, null=True, verbose_name='外部条码')),
                ('bz', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('check1no', models.CharField(max_length=50, verbose_name='检验报告编号')),
                ('pas', models.IntegerField(verbose_name='原料状态')),
                ('qcmen', models.CharField(blank=True, max_length=30, null=True, verbose_name='检验人')),
                ('gyscode', models.CharField(max_length=50, verbose_name='供应商代码')),
                ('rkck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_rmaterial.Stockinfo', verbose_name='入库仓库')),
                ('ylid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_rmaterial.Ylinfo', verbose_name='原料代码')),
            ],
            options={
                'verbose_name': '原料入库',
                'verbose_name_plural': '原料入库表',
                'db_table': 'enterstock',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ylid', models.CharField(max_length=50, verbose_name='原料代码')),
                ('ylname', models.CharField(max_length=50, verbose_name='原料名称')),
                ('quantity', models.FloatField(verbose_name='在库数量')),
                ('qcsl', models.FloatField(blank=True, null=True, verbose_name='上期结存')),
                ('qa_hg', models.FloatField(blank=True, null=True, verbose_name='合格数量')),
                ('bz', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_rmaterial.Stockinfo', verbose_name='仓库编号')),
            ],
            options={
                'verbose_name': '原料结存',
                'verbose_name_plural': '原料结存表',
                'db_table': 'stock',
            },
        ),
    ]
