# Generated by Django 2.0.1 on 2019-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_rmaterial', '0003_auto_20190103_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llyl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq', models.DateTimeField(verbose_name='日期')),
                ('ylid', models.CharField(max_length=50, verbose_name='原料代码')),
                ('ylname', models.CharField(max_length=50, verbose_name='原料名称')),
                ('sl', models.FloatField(verbose_name='理论用量')),
                ('yllx', models.IntegerField(blank=True, null=True, verbose_name='原料类型')),
                ('stockid', models.CharField(blank=True, max_length=20, null=True, verbose_name='仓库编号')),
                ('zsdzl', models.FloatField(blank=True, null=True, verbose_name='整数袋重量')),
                ('scxh', models.IntegerField(blank=True, null=True, verbose_name='生产线号')),
                ('bz', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '原料领用计算',
                'verbose_name_plural': '原料领用计算',
                'db_table': 'llyl',
            },
        ),
    ]
