# Generated by Django 2.0.1 on 2019-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_rmaterial', '0004_llyl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llyl',
            name='sl',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='理论用量'),
        ),
        migrations.AlterField(
            model_name='llyl',
            name='zsdzl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='整数袋重量'),
        ),
    ]
