# Generated by Django 2.0.1 on 2019-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_rmaterial', '0005_auto_20190109_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='llyl',
            name='spl',
            field=models.CharField(default='', max_length=20, verbose_name='计划单号'),
        ),
    ]
