# Generated by Django 2.0.1 on 2018-06-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bc_rmaterial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pb',
            fields=[
                ('pbbh', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='配方编号')),
                ('pbname', models.CharField(blank=True, max_length=50, null=True, verbose_name='配方名称')),
                ('pftype', models.IntegerField(blank=True, default=0, null=True, verbose_name='配方类型(0：标准配方；1：比例配方)')),
                ('shr', models.CharField(blank=True, max_length=50, null=True, verbose_name='审核人')),
                ('fwrsx', models.IntegerField(blank=True, null=True, verbose_name='防交叉污染生产顺序')),
                ('scxh', models.IntegerField(blank=True, null=True, verbose_name='默认生产线')),
                ('pfsj', models.DateTimeField(auto_now_add=True, null=True, verbose_name='配方建立日期')),
                ('sh', models.BooleanField(default=True, verbose_name='审核状态')),
                ('bz', models.CharField(blank=True, max_length=220, null=True, verbose_name='备注')),
                ('yx', models.BooleanField(default=True, verbose_name='有效配方')),
            ],
            options={
                'verbose_name': '配方',
                'verbose_name_plural': '配方',
                'db_table': 'pb',
            },
        ),
        migrations.CreateModel(
            name='Pbf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plno', models.SmallIntegerField(verbose_name='称量顺序号')),
                ('bzgl', models.FloatField(verbose_name='标准值')),
                ('topz', models.FloatField(verbose_name='上限值')),
                ('lowz', models.FloatField(verbose_name='下限值')),
                ('dw', models.CharField(blank=True, default='kg', max_length=20, null=True, verbose_name='单位(Kg or g)')),
                ('cno', models.IntegerField(blank=True, null=True, verbose_name='使用电子秤端口号')),
                ('jno', models.IntegerField(verbose_name='加料顺序')),
                ('lt', models.BooleanField(default=True, verbose_name='称零头')),
                ('zsxs', models.BooleanField(default=True, verbose_name='外部追溯显示')),
                ('pbbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_formula.Pb', verbose_name='配方编号(与主表关联)')),
                ('ylid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_rmaterial.Ylinfo', verbose_name='原料代码')),
            ],
            options={
                'verbose_name': '配方副表',
                'verbose_name_plural': '配方副表',
                'db_table': 'pbf',
            },
        ),
    ]
