# Generated by Django 2.0.1 on 2018-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb',
            name='bz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='pb',
            name='pftype',
            field=models.CharField(max_length=15, verbose_name='配方类型'),
        ),
        migrations.AlterField(
            model_name='pb',
            name='scxh',
            field=models.IntegerField(blank=True, null=True, verbose_name='默认生产线'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='bzgl',
            field=models.IntegerField(verbose_name='标准值'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='dw',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='lowz',
            field=models.IntegerField(verbose_name='下限'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='topz',
            field=models.IntegerField(verbose_name='上限'),
        ),
    ]
