# Generated by Django 2.0.1 on 2019-01-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pb',
            options={'verbose_name': '配方', 'verbose_name_plural': '配方信息'},
        ),
    ]
