# Generated by Django 2.0.1 on 2018-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb',
            name='pftype',
            field=models.IntegerField(blank=True, choices=[(0, '标准配方'), (1, '比例配方')], default=0, null=True, verbose_name='配方类型(0：标准配方；1：比例配方)'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='dw',
            field=models.CharField(blank=True, choices=[('0', 'kg'), ('1', 'g')], default='0', max_length=20, null=True, verbose_name='单位(Kg or g)'),
        ),
    ]
