# Generated by Django 2.0.1 on 2018-09-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_formula', '0002_auto_20180921_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbf',
            name='bzgl',
            field=models.FloatField(verbose_name='标准值'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='lowz',
            field=models.FloatField(verbose_name='下限'),
        ),
        migrations.AlterField(
            model_name='pbf',
            name='topz',
            field=models.FloatField(verbose_name='上限'),
        ),
    ]
